export interface EventStyle {
    title: string;
    notes: string;
    start: Date;
    end: Date;
    bgColor: string;
    user: {
        _id: string;
        name: string;
    };
}


// Generated by https://quicktype.io

export interface EventTypes {
    id: string;
    title: string;
    notes: string;
    start: Date;
    end: Date;
    user: {
        uid: string
        name: string
    };
}

