// Generated by https://quicktype.io

export interface CalendarEventBoxTypes {
    title: string;
    notes: string;
    start: string;
    end: string;
    bgColor: string;
    user: User;
}

export interface User {
    id: string;
    name: string;
}
